"""Self-test for arc_common.tokenizer and arc_common.scoring against the
synthetic data generated by generator.py. Run locally, no GPU/torch needed."""
import json
from pathlib import Path

from arc_common.scoring import build_submission_template, score_submission, validate_submission
from arc_common.tokenizer import decode_grid, encode_grid, encode_prompt, encode_target, decode_prediction

DATA = Path(__file__).parent / "data" / "synthetic"


def test_tokenizer_roundtrip():
    challenges = json.loads((DATA / "train_challenges.json").read_text())
    n = 0
    for task in challenges.values():
        for pair in task["train"]:
            for grid in (pair["input"], pair["output"]):
                tokens = encode_grid(grid)
                assert decode_grid(tokens) == grid, f"roundtrip mismatch: {grid} -> {tokens} -> {decode_grid(tokens)}"
                n += 1
    print(f"tokenizer roundtrip OK on {n} grids")


def test_prompt_and_target_shapes():
    challenges = json.loads((DATA / "train_challenges.json").read_text())
    solutions = json.loads((DATA / "train_solutions.json").read_text())
    task_id = next(iter(challenges))
    task = challenges[task_id]
    prompt = encode_prompt(task, test_index=0)
    target = encode_target(solutions[task_id][0])
    assert prompt[0] == 14  # BOS
    assert prompt[-1] == 12  # ends at GRID_OUT
    assert target[-1] == 15  # EOS
    # a model conditioned on `prompt` should predict `target`; decoding target minus EOS
    # must recover the ground truth grid exactly
    decoded = decode_prediction(target)
    assert decoded == solutions[task_id][0]
    print("prompt/target encoding OK:", "prompt len", len(prompt), "target len", len(target))


def test_scoring_perfect_and_wrong():
    challenges = json.loads((DATA / "heldout_challenges.json").read_text())
    solutions = json.loads((DATA / "heldout_solutions.json").read_text())

    assert validate_submission(build_submission_template(challenges), challenges) == []

    # perfect predictor: attempt_1 = ground truth
    perfect = {
        tid: [{"attempt_1": gt, "attempt_2": [[0]]} for gt in sols]
        for tid, sols in solutions.items()
    }
    result = score_submission(perfect, solutions)
    assert result["score"] == 1.0, result["score"]
    print("perfect-predictor score:", result["score"])

    # trivial wrong predictor: copy the (unrelated) test input as both attempts
    trivial = {
        tid: [{"attempt_1": challenges[tid]["test"][i]["input"], "attempt_2": [[0]]} for i in range(len(sols))]
        for tid, sols in solutions.items()
    }
    result = score_submission(trivial, solutions)
    print("trivial (copy-input) predictor score:", result["score"])
    assert result["score"] < 0.05, "trivial baseline should almost never accidentally match"


if __name__ == "__main__":
    test_tokenizer_roundtrip()
    test_prompt_and_target_shapes()
    test_scoring_perfect_and_wrong()
    print("ALL OK")
