"""Self-test for arc_common.symbolic and arc_common.tta against the synthetic
data generated by generator.py. Run locally, no GPU/torch needed -- this
validates the Phase 3 neuro-symbolic plumbing cheaply before spending Kaggle
GPU time retraining the three architectures with the verifier attached."""
import json
import random
from pathlib import Path

from arc_common.symbolic import symbolic_predict
from arc_common.tta import D4, combined_predict, tta_predict, transform_task

DATA = Path(__file__).parent / "data" / "synthetic"


def load(name):
    challenges = json.loads((DATA / f"{name}_challenges.json").read_text())
    solutions = json.loads((DATA / f"{name}_solutions.json").read_text())
    return challenges, solutions


def test_symbolic_solves_train_eval_and_heldout():
    for split in ["train_eval", "heldout"]:
        challenges, solutions = load(split)
        n, correct = 0, 0
        for task_id, task in challenges.items():
            for i in range(len(task["test"])):
                pred = symbolic_predict(task, i)
                gt = solutions[task_id][i]
                n += 1
                correct += int(pred == gt)
        rate = correct / n
        print(f"symbolic_predict exact-match on {split}: {correct}/{n} ({rate:.3f})")
        # Expected ~1.0: the search space (14 structural x ~136 color ops) is a strict
        # superset of the generator's own 4x4 struct_then_color primitives, so a
        # consistent program should exist for every task, including held-out
        # (structural, color) pairings never seen during neural training -- the
        # symbolic verifier doesn't need training, it searches fresh every task.
        assert rate > 0.95, f"expected the symbolic verifier to solve nearly all of {split}, got {rate:.3f}"


def test_symbolic_abstains_on_unrelated_grids():
    task = {
        "train": [
            {"input": [[1, 2], [3, 4]], "output": [[9, 9], [9, 9]]},
            {"input": [[5, 6], [7, 8]], "output": [[0, 1], [2, 3]]},
        ],
        "test": [{"input": [[1, 1], [1, 1]]}],
    }
    pred = symbolic_predict(task, 0)
    assert pred is None, f"expected no consistent program for unrelated demo pairs, got {pred}"
    print("symbolic_predict correctly abstains when no program is consistent")


def test_d4_roundtrip_is_identity_on_predict_fn_output():
    challenges, _ = load("train_eval")
    task = next(iter(challenges.values()))

    def echo_predict(t, idx):
        return t["test"][idx]["input"]

    for name, fwd, inv in D4:
        t_task = transform_task(task, fwd)
        pred = echo_predict(t_task, 0)
        recovered = inv(pred)
        assert recovered == task["test"][0]["input"], f"{name}: forward+inverse+echo did not round-trip"
    print(f"D4 forward/inverse round-trip OK across all {len(D4)} views")


def test_tta_majority_vote_recovers_correct_answer_from_noisy_proposer():
    challenges, solutions = load("train_eval")
    task_id = next(iter(challenges))
    task = challenges[task_id]
    gt = solutions[task_id][0]
    rng = random.Random(0)

    def noisy_predict(t, idx):
        # "correct" in this view's own frame is just the identity transform of gt,
        # but tta_predict doesn't know that -- it only sees this callback's raw
        # output and inverts it itself. Simulate a proposer that's right most of
        # the time per-view but occasionally emits garbage.
        if rng.random() < 0.7:
            return t["test"][idx]["input"]  # placeholder "correct-in-this-view" signal
        return [[9]]

    # Use a deterministic proposer that is always "correct" (echoes the transformed
    # input back, which tta_predict will invert) to check the pure round-trip path
    # end-to-end via majority vote when every view agrees.
    def perfect_echo(t, idx):
        return t["test"][idx]["input"]

    pred, candidates = tta_predict(task, 0, perfect_echo)
    assert pred == task["test"][0]["input"], "majority vote over 8 agreeing views should recover the exact input"
    assert len(candidates) == 8
    print("tta_predict majority vote OK: all 8 views agree and round-trip correctly")


def test_combined_predict_prefers_symbolic_over_wrong_neural():
    challenges, solutions = load("heldout")
    task_id = next(iter(challenges))
    task = challenges[task_id]
    gt = solutions[task_id][0]

    def always_wrong(t, idx):
        return [[9, 9], [9, 9]]

    pred, source = combined_predict(task, 0, always_wrong, use_tta=True, use_symbolic=True)
    assert source == "symbolic", f"expected symbolic verifier to fire on a held-out synthetic task, got {source}"
    assert pred == gt, "symbolic-verified program should reproduce the exact ground truth"
    print("combined_predict correctly overrides a wrong neural proposer with the symbolic verifier")

    pred2, source2 = combined_predict(task, 0, always_wrong, use_tta=True, use_symbolic=False)
    assert source2 == "neural"
    assert pred2 != gt
    print("combined_predict falls through to the (wrong) neural proposer when use_symbolic=False")


if __name__ == "__main__":
    test_symbolic_solves_train_eval_and_heldout()
    test_symbolic_abstains_on_unrelated_grids()
    test_d4_roundtrip_is_identity_on_predict_fn_output()
    test_tta_majority_vote_recovers_correct_answer_from_noisy_proposer()
    test_combined_predict_prefers_symbolic_over_wrong_neural()
    print("ALL OK")
